apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: my-cluster
nodes:
- role: control-plane
- role: worker
  labels:
    appFamily: foo
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
